export const sampleAttendees = [
  {
    id: '1',
    name: 'DJ Polita',
    photo_url: '/avatars/polita.jpg',
    room: 'Habitación 1',
    previous_editions: ['aliens', 'love', 'awaked', 'human', 'hippie', 'metro', 'inferno'],
    group_names: ['DJ', 'Founding'],
  },
  {
    id: '2',
    name: 'AdolFit',
    photo_url: '/avatars/adolfit.jpg',
    room: 'Habitación 2',
    previous_editions: ['aliens', 'love', 'awaked', 'human', 'hippie'],
    group_names: ['DJ', 'Sports'],
  },
  {
    id: '3',
    name: 'Capreini',
    photo_url: '/avatars/capreini.jpg',
    room: 'Habitación 3',
    previous_editions: ['love', 'awaked', 'human', 'hippie', 'metro', 'inferno'],
    group_names: ['DJ', 'Founding'],
  },
  {
    id: '4',
    name: 'V4',
    photo_url: '/avatars/v4.jpg',
    room: 'Habitación 4',
    previous_editions: ['human', 'hippie', 'metro', 'inferno'],
    group_names: ['DJ'],
  },
  {
    id: '5',
    name: 'Santini',
    photo_url: '/avatars/santini.jpg',
    room: 'Habitación 5',
    previous_editions: ['metro', 'inferno'],
    group_names: ['Party'],
  },
  {
    id: '6',
    name: 'María',
    photo_url: '/avatars/maria.jpg',
    room: 'Habitación 6',
    previous_editions: ['aliens', 'love', 'awaked', 'human'],
    group_names: ['Founding', 'Kitchen'],
  },
  {
    id: '7',
    name: 'Carlos',
    photo_url: '/avatars/carlos.jpg',
    room: 'Habitación 7',
    previous_editions: ['awaked', 'human', 'hippie'],
    group_names: ['Sports', 'BBQ'],
  },
  {
    id: '8',
    name: 'Ana',
    photo_url: '/avatars/ana.jpg',
    room: 'Habitación 1',
    previous_editions: ['hippie', 'metro', 'inferno'],
    group_names: ['Kitchen', 'Decoration'],
  },
  {
    id: '9',
    name: 'Pablo',
    photo_url: '/avatars/pablo.jpg',
    room: 'Habitación 2',
    previous_editions: ['inferno'],
    group_names: ['Party', 'BBQ'],
  },
  {
    id: '10',
    name: 'Laura',
    photo_url: '/avatars/laura.jpg',
    room: 'Habitación 3',
    previous_editions: ['metro', 'inferno'],
    group_names: ['Decoration'],
  },
  {
    id: '11',
    name: 'Javier',
    photo_url: '/avatars/javier.jpg',
    room: 'Habitación 4',
    previous_editions: ['aliens', 'love', 'awaked'],
    group_names: ['Founding', 'BBQ'],
  },
  {
    id: '12',
    name: 'Sofía',
    photo_url: '/avatars/sofia.jpg',
    room: 'Habitación 5',
    previous_editions: ['human', 'hippie', 'metro', 'inferno'],
    group_names: ['Kitchen'],
  },
]

export const categories = [
  {
    id: 'cat1',
    name: 'Caposo (mejor vestido)',
    order: 1,
    dj_only: false,
  },
  {
    id: 'cat2',
    name: 'Capín (más gracioso)',
    order: 2,
    dj_only: false,
  },
  {
    id: 'cat3',
    name: 'Caporro (más loco)',
    order: 3,
    dj_only: false,
  },
  {
    id: 'cat4',
    name: 'Capacañón (mejor bailarín)',
    order: 4,
    dj_only: false,
  },
  {
    id: 'cat5',
    name: 'Bizacap (mejor sesión de música)',
    order: 5,
    dj_only: true,
  },
  {
    id: 'cat6',
    name: 'Capamante (más cariñoso)',
    order: 6,
    dj_only: false,
  },
]

// Room background images mapping (to be added later)
export const roomBackgrounds = {
  'Habitación 1': '/rooms/room1.jpg',
  'Habitación 2': '/rooms/room2.jpg',
  'Habitación 3': '/rooms/room3.jpg',
  'Habitación 4': '/rooms/room4.jpg',
  'Habitación 5': '/rooms/room5.jpg',
  'Habitación 6': '/rooms/room6.jpg',
  'Habitación 7': '/rooms/room7.jpg',
}
